 # $$$$$$$\            $$\ $$$$$$$\                                $$$$$$\   $$\
 # $$  __$$\           $$ |$$  __$$\                               \_$$  _|  $$ |
 # $$ |  $$ | $$$$$$\  $$ |$$ |  $$ | $$$$$$\   $$$$$$\   $$$$$$\    $$ |  $$$$$$\    $$$$$$\  $$$$$$\$$$$\   $$$$$$$\
 # $$ |  $$ |$$  __$$\ $$ |$$ |  $$ |$$  __$$\ $$  __$$\ $$  __$$\   $$ |  \_$$  _|  $$  __$$\ $$  _$$  _$$\ $$  _____|
 # $$ |  $$ |$$$$$$$$ |$$ |$$ |  $$ |$$ |  \__|$$ /  $$ |$$ /  $$ |  $$ |    $$ |    $$$$$$$$ |$$ / $$ / $$ |\$$$$$$\
 # $$ |  $$ |$$   ____|$$ |$$ |  $$ |$$ |      $$ |  $$ |$$ |  $$ |  $$ |    $$ |$$\ $$   ____|$$ | $$ | $$ | \____$$\
 # $$$$$$$  |\$$$$$$$\ $$ |$$$$$$$  |$$ |      \$$$$$$  |$$$$$$$  |$$$$$$\   \$$$$  |\$$$$$$$\ $$ | $$ | $$ |$$$$$$$  |
 # \_______/  \_______|\__|\_______/ \__|       \______/ $$  ____/ \______|   \____/  \_______|\__| \__| \__|\_______/
 #                                                       $$ |
 #                                                       $$ |
 #                                                       \__|

  ##################################################
  #                   Language                     #
  ##################################################


language: "en"


  ##################################################
  #                    Message                     #
  ##################################################


drop-message-allow: true # Allowing the plugin to send messages about the player throwing an item

reload-message-allow: true # Allow the plugin to send a configuration reload message

broadcast-message-allow: true # Allow the plugin to send automatic messages

broadcast-interval: 300 # Interval in seconds between messages

distance-player-to-object: 25 # Distance where there should be no players



  ##################################################
  #                   Delete Item                  #
  ##################################################


item-removal-time: 300  # Time for item removal in seconds

